
# ============================================
#     🔥 CVETIK-VPN 🔥
#     💎 ПРЕМИУМ ДОСТУП 💎
#     🌍 22+ СЕРВЕРА ПО ВСЕМУ МИРУ
#     📡 БЕЗЛИМИТНЫЙ ТРАФИК
#     🚀 РАБОТАЕТ ВСЕГДА
#     📢 КАНАЛ: @ForgeModsIK
#     👑 СОЗДАТЕЛЬ: @Pr1meRUst
# ============================================


[Interface]
Address = 172.16.9.81
DNS = 172.16.0.1
Jc = 2
Jmin = 16
Jmax = 63
S1 = 858
S2 = 561
H1 = 2138626506
H2 = 222057921
H3 = 265424867
H4 = 819855531
PrivateKey = SBvJYNLeQwr/tM4/UXgiWcFz9MCKhKmhuAcf5CGQnls=
[Peer]
PublicKey = qIaa6NyjlSkzqW3Y43jDXaoPpeBH+YGh2gnFEwEeQUY=
PresharedKey = Q18mHvauIOrXj8ys12RqqRv9y+/ynXnTzngTcICSuKc=
AllowedIPs = 0.0.0.0/0
Endpoint = 72.56.50.122:64161
PersistentKeepalive = 25
