
# ============================================
#     🔥 CVETIK-VPN 🔥
#     💎 ПРЕМИУМ ДОСТУП 💎
#     🌍 22+ СЕРВЕРА ПО ВСЕМУ МИРУ
#     📡 БЕЗЛИМИТНЫЙ ТРАФИК
#     🚀 РАБОТАЕТ ВСЕГДА
#     📢 КАНАЛ: @ForgeModsIK
#     👑 СОЗДАТЕЛЬ: @Pr1meRUst
# ============================================


[Interface]
Address = 10.100.88.8
DNS = 10.101.0.1, 8.8.8.8
Jc = 10
Jmin = 20
Jmax = 84
S1 = 796
S2 = 791
H1 = 1306428388
H2 = 889083146
H3 = 925965220
H4 = 901120763
PrivateKey = UEf8/voA7xAuSbQ1FjkKW3tqOGg8wBS10r7e/MpEZ0I=
[Peer]
PublicKey = hGG1y8v1tDBZQyGoKcZKooyx6CacRlgcPmF7uSttzhg=
PresharedKey = Q18mHvauIOrXj8ys12RqqRv9y+/ynXnTzngTcICSuKc=
AllowedIPs = 0.0.0.0/0
Endpoint = 185.103.200.8:28119
PersistentKeepalive = 25
