
# ============================================
#     🔥 CVETIK-VPN 🔥
#     💎 ПРЕМИУМ ДОСТУП 💎
#     🌍 22+ СЕРВЕРА ПО ВСЕМУ МИРУ
#     📡 БЕЗЛИМИТНЫЙ ТРАФИК
#     🚀 РАБОТАЕТ ВСЕГДА
#     📢 КАНАЛ: @ForgeModsIK
#     👑 СОЗДАТЕЛЬ: @Pr1meRUst
# ============================================


[Interface]
Address = 172.17.24.96
DNS = 172.16.0.1
Jc = 9
Jmin = 17
Jmax = 47
S1 = 1226
S2 = 933
H1 = 287973719
H2 = 720834990
H3 = 1857194443
H4 = 920665164
PrivateKey = MJ8jiuWPfBMlQEqtaLI6/h5MWoyiRBI8phl2eY6gPlo=
[Peer]
PublicKey = rcIgmewdWy9lvMqERblxqHdZP+Rt4UPPSscD36MpmQ8=
PresharedKey = Q18mHvauIOrXj8ys12RqqRv9y+/ynXnTzngTcICSuKc=
AllowedIPs = 0.0.0.0/0
Endpoint = 72.56.62.244:4959
PersistentKeepalive = 25
