
# ============================================
#     🔥 CVETIK-VPN 🔥
#     💎 ПРЕМИУМ ДОСТУП 💎
#     🌍 22+ СЕРВЕРА ПО ВСЕМУ МИРУ
#     📡 БЕЗЛИМИТНЫЙ ТРАФИК
#     🚀 РАБОТАЕТ ВСЕГДА
#     📢 КАНАЛ: @ForgeModsIK
#     👑 СОЗДАТЕЛЬ: @Pr1meRUst
# ============================================


[Interface]
Address = 10.100.222.58
DNS = 10.101.0.1, 8.8.8.8
Jc = 2
Jmin = 7
Jmax = 45
S1 = 954
S2 = 77
H1 = 2099237655
H2 = 1385987290
H3 = 1445105174
H4 = 396267723
PrivateKey = +AUOlVgnWM97eFJ8z2ulcSXDbDNzPTBddwLUqDKoWmw=
[Peer]
PublicKey = Sy/VW82UUnpHEsQ9BEi1vV8uep1ExceZHJCVHNiteS8=
PresharedKey = Q18mHvauIOrXj8ys12RqqRv9y+/ynXnTzngTcICSuKc=
AllowedIPs = 0.0.0.0/0
Endpoint = 185.103.200.7:39390
PersistentKeepalive = 25
