
# ============================================
#     🔥 CVETIK-VPN 🔥
#     💎 ПРЕМИУМ ДОСТУП 💎
#     🌍 22+ СЕРВЕРА ПО ВСЕМУ МИРУ
#     📡 БЕЗЛИМИТНЫЙ ТРАФИК
#     🚀 РАБОТАЕТ ВСЕГДА
#     📢 КАНАЛ: @ForgeModsIK
#     👑 СОЗДАТЕЛЬ: @Pr1meRUst
# ============================================


[Interface]
Address = 10.100.56.61
DNS = 10.101.0.1, 8.8.8.8
Jc = 4
Jmin = 18
Jmax = 52
S1 = 932
S2 = 128
H1 = 310088025
H2 = 1198667892
H3 = 1532877801
H4 = 910701683
PrivateKey = 8KLc0gvFp6fTt1cBRuZtIVievnQjTYB6H+ltdfYdE3o=
[Peer]
PublicKey = b95zAqp4cU4cKJVzxLoeOUhy9D+FJ4TeyqRoyPJc9XM=
PresharedKey = Q18mHvauIOrXj8ys12RqqRv9y+/ynXnTzngTcICSuKc=
AllowedIPs = 0.0.0.0/0
Endpoint = 72.56.62.15:43766
PersistentKeepalive = 25
